services:
  db:
    image: postgres:16
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"

  postgrest:
    image: postgrest/postgrest:latest
    env_file:
      - .env
    environment:
      PGRST_DB_URI: "postgres://${DB_USER}:${DB_PASS}@db:5432/${DB_NAME}"
      PGRST_DB_SCHEMA: "public"
      PGRST_DB_ANON_ROLE: "${DB_USER}"
      PGRST_SERVER_PORT: "3000"
    depends_on:
      - db

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - postgrest
